CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    product_name VARCHAR(100) NOT NULL,

    quantity INTEGER NOT NULL
        CHECK (quantity >= 1),

    unit_price NUMERIC(12, 0) NOT NULL
        CHECK (unit_price >= 0),

    order_id BIGINT NOT NULL,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE
);