CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    price NUMERIC(12, 0) NOT NULL CHECK (price >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    category_id INTEGER NOT NULL,
    description VARCHAR(1000),
    image_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO products (
    product_name,
    price,
    stock,
    category_id,
    description,
    image_url
) VALUES (
    'ショートケーキ',
    480,
    20,
    1,
    'ふわふわのスポンジとたっぷりの生クリーム、いちごを使用した定番のケーキです。',
    '/images/shortcake.jpg'
);


INSERT INTO products (
    product_name,
    price,
    stock,
    category_id,
    description,
    image_url
) VALUES (
    'チーズケーキ',
    520,
    15,
    1,
    '北海道産クリームチーズを使用した、濃厚でなめらかなベイクドチーズケーキです。',
    '/images/cheesecake.jpg'
);


INSERT INTO products (
    product_name,
    price,
    stock,
    category_id,
    description,
    image_url
) VALUES (
    'ガトーショコラ',
    550,
    12,
    1,
    'カカオの風味豊かなチョコレートを贅沢に使用した、しっとり食感のケーキです。',
    '/images/gateau-chocolat.jpg'
);


INSERT INTO products (
    product_name,
    price,
    stock,
    category_id,
    description,
    image_url
) VALUES (
    'バタークッキー',
    320,
    40,
    2,
    '発酵バターを使用し、香ばしく焼き上げたサクサク食感のクッキーです。',
    '/images/butter-cookie.jpg'
);


INSERT INTO products (
    product_name,
    price,
    stock,
    category_id,
    description,
    image_url
) VALUES (
    'マドレーヌ',
    280,
    30,
    2,
    '焦がしバターの香りが広がる、しっとりとした食感の焼き菓子です。',
    '/images/madeleine.jpg'
);


/*
【productsテーブルの説明】

id
    商品を識別するための商品IDです。
    商品登録時に1、2、3のように自動採番されます。
    PRIMARY KEYのため、同じIDは登録できません。

name
    商品名です。
    最大100文字で、NOT NULLにより入力必須です。

price
    商品価格です。
    NUMERIC(12, 0)により、小数なしの最大12桁の金額を保存できます。
    CHECK (price >= 0)により、マイナス価格は登録できません。

stock
    商品の在庫数です。
    省略した場合はDEFAULT 0により0が登録されます。
    CHECK (stock >= 0)により、マイナス在庫は登録できません。

category_id
    商品が属するカテゴリーのIDです。
    例として、1をケーキ、2を焼き菓子として使用しています。

description
    商品の説明文です。
    最大1000文字まで保存できます。
    NOT NULLがないため、省略することもできます。

image_url
    商品画像のURLまたは画像ファイルのパスです。
    例：/images/shortcake.jpg
    NOT NULLがないため、画像がない商品も登録できます。

created_at
    商品を登録した日時です。
    INSERT時に省略すると、現在日時が自動的に登録されます。

updated_at
    商品情報の更新日時として使用する列です。
    初回登録時には現在日時が自動的に登録されます。
    PostgreSQLではUPDATE時に自動変更されないため、
    商品更新SQLでupdated_at = CURRENT_TIMESTAMPを指定します。

【Javaコードとの対応】

id          → Productクラスのid
name        → Productクラスのname
price       → Productクラスのprice
stock       → Productクラスのstock
description → Productクラスのdescription
image_url   → ProductクラスのimageUrl

ProductDAOで使用しているid、name、price、stock、
description、image_urlと列名が一致しています。
*/