CREATE TABLE shopping_orders (
    shopping_order_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    member_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    payment_method VARCHAR(30) NOT NULL,

    total_amount NUMERIC(18, 0) NOT NULL
        CHECK (total_amount >= 0),

    order_status VARCHAR(20) NOT NULL
        DEFAULT 'ORDERED',

    checkout_token VARCHAR(36) NOT NULL
        UNIQUE,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_shopping_orders_member
        FOREIGN KEY (member_id)
        REFERENCES members(member_id),

    CONSTRAINT ck_shopping_orders_payment
        CHECK (
            payment_method IN (
                'credit',
                'bank',
                'cash_on_delivery',
                'convenience_store'
            )
        ),

    CONSTRAINT ck_shopping_orders_status
        CHECK (
            order_status IN (
                'ORDERED',
                'CANCELLED',
                'COMPLETED'
            )
        )
);


CREATE TABLE shopping_order_items (
    shopping_order_item_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    shopping_order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(100) NOT NULL,

    unit_price NUMERIC(12, 0) NOT NULL
        CHECK (unit_price >= 0),

    quantity INTEGER NOT NULL
        CHECK (quantity >= 1),

    CONSTRAINT fk_shopping_order_items_order
        FOREIGN KEY (shopping_order_id)
        REFERENCES shopping_orders(
            shopping_order_id
        )
        ON DELETE CASCADE,

    CONSTRAINT fk_shopping_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);